const actionTypes = {
  ADD_PERIOD: "ADD_PERIOD",
  REMOVE_PERIOD: "REMOVE_PERIOD",
  ADD_EVENT: "ADD_EVENT",
  REMOVE_EVENT: "REMOVE_EVENT",
  ADD_SCENE: "ADD_SCENE",
  REMOVE_SCENE: "REMOVE_SCENE"
}

export default actionTypes
